services:
  redis:
    image: redis:7-alpine
    container_name: redis-demo
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  python-app:
    build: ./redis_demo
    container_name: python-redis
    volumes:
      - ./redis_demo:/app
    working_dir: /app
    tty: true          
    stdin_open: true
    depends_on:
      - redis

volumes:
  redis_data:
